# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataInput(object):
    def setupUi(self, DataInput):
        DataInput.setObjectName("DataInput")
        DataInput.resize(640, 480)
        self.titleLabel = QtWidgets.QLabel(DataInput)
        self.titleLabel.setGeometry(QtCore.QRect(20, 10, 561, 61))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.btnAddPath = QtWidgets.QPushButton(DataInput)
        self.btnAddPath.setGeometry(QtCore.QRect(486, 78, 104, 32))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.btnAddPath.setFont(font)
        self.btnAddPath.setObjectName("btnAddPath")
        self.verticalLayoutWidget = QtWidgets.QWidget(DataInput)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 130, 541, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.btnBoxConfirm = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.btnBoxConfirm.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnBoxConfirm.setFont(font)
        self.btnBoxConfirm.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxConfirm.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBoxConfirm.setObjectName("btnBoxConfirm")
        self.verticalLayout.addWidget(self.btnBoxConfirm)

        self.retranslateUi(DataInput)
        self.btnBoxConfirm.accepted.connect(DataInput.accept)
        self.btnBoxConfirm.rejected.connect(DataInput.reject)
        QtCore.QMetaObject.connectSlotsByName(DataInput)

    def retranslateUi(self, DataInput):
        _translate = QtCore.QCoreApplication.translate
        DataInput.setWindowTitle(_translate("DataInput", "Dialog"))
        self.titleLabel.setText(_translate("DataInput", "请输入数据(输入多个数据请用Enter换行隔开)"))
        self.btnAddPath.setText(_translate("DataInput", "添加路径"))
