const musicPath=[{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-01 Lonely Deemo (Skit).mp3",title:"Lonely Deemo (Skit)",artist:"FabricFactory",coverUrl:"B:/python-test/project2/public_GUI/cover/Lonely Deemo (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-02 Falling Girl (Skit).mp3",title:"Falling Girl (Skit)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Falling Girl (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-03 Budding (Skit).mp3",title:"Budding (Skit)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Budding (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-04 Growing (Skit).mp3",title:"Growing (Skit)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Growing (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-05 I miss my home (Skit).mp3",title:"I miss my home (Skit)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/I miss my home (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-06 Leaves (Skit).mp3",title:"Leaves (Skit)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Leaves (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-07 Where It Goes (Skit).mp3",title:"Where It Goes (Skit)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Where It Goes (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-08 The New Tree (Skit).mp3",title:"The New Tree (Skit)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/The New Tree (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-09 The Key (Skit).mp3",title:"The Key (Skit)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/The Key (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-10 You Cannot Go (Skit).mp3",title:"You Cannot Go (Skit)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/You Cannot Go (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-11 Going Home (Skit).mp3",title:"Going Home (Skit)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Going Home (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-12 Goodbye (Skit).mp3",title:"Goodbye (Skit)",artist:"Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Goodbye (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-13 Where You Are Not (Skit).mp3",title:"Where You Are Not (Skit)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Where You Are Not (Skit).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-14 Alice good night (ED2).mp3",title:"Alice good night (ED2)",artist:"Yuk-Cheung Chun Vocal by Riin",coverUrl:"B:/python-test/project2/public_GUI/cover/Alice good night (ED2).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-15 Deemo Main Theme (Game Version).mp3",title:"Deemo Title Song (Game Version)",artist:"Tzu-Chieh Wen",coverUrl:"B:/python-test/project2/public_GUI/cover/Deemo Title Song (Game Version).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-16 Loading ~Intro~.mp3",title:"Loading ~Intro~",artist:"Rayark",coverUrl:"B:/python-test/project2/public_GUI/cover/Loading ~Intro~.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-17 Deemo Check Music.mp3",title:"Deemo Check Music",artist:"Rayark",coverUrl:"B:/python-test/project2/public_GUI/cover/Deemo Check Music.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-18 Day (BGM).mp3",title:"Day (BGM)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Day (BGM).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-19 Night (BGM).mp3",title:"Night (BGM)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Night (BGM).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-20 Basement (BGM).mp3",title:"Basement (BGM)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Basement (BGM).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-21 Top (BGM).mp3",title:"Top (BGM)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Top (BGM).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-22 Reverse (Short Version).mp3",title:"Reverse (Short Version)",artist:"V.K",coverUrl:"B:/python-test/project2/public_GUI/cover/Reverse (Short Version).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-23 Entrance (Old Version).mp3",title:"Entrance (Old Version)",artist:"Ice",coverUrl:"B:/python-test/project2/public_GUI/cover/Entrance (Old Version).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-24 Deemo Main Theme (Website Version).mp3",title:"Deemo Main Theme (Website Version)",artist:"FabricFactory & Chamber Chu",coverUrl:"B:/python-test/project2/public_GUI/cover/Deemo Main Theme (Website Version).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-25 Daylight.mp3",title:"Daylight",artist:"Tatsh",coverUrl:"B:/python-test/project2/public_GUI/cover/Daylight.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-26 From RestedPoint.mp3",title:"From RestedPoint",artist:"Tatsh",coverUrl:"B:/python-test/project2/public_GUI/cover/From RestedPoint.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-27 Rise Up.mp3",title:"Rise Up",artist:"Tatsh",coverUrl:"B:/python-test/project2/public_GUI/cover/Rise Up.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-28 Rebellion.mp3",title:"Rebellion",artist:"Tatsh",coverUrl:"B:/python-test/project2/public_GUI/cover/Rebellion.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-29 Need Your Luv.mp3",title:"Need Your Luv",artist:"Tatsh",coverUrl:"B:/python-test/project2/public_GUI/cover/Need Your Luv.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-30 Earlier Then Today.mp3",title:"Earlier Than Today",artist:"Eshen",coverUrl:"B:/python-test/project2/public_GUI/cover/Earlier Than Today.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-31 For sis.mp3",title:"For sis",artist:"Eshen",coverUrl:"B:/python-test/project2/public_GUI/cover/For sis.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-32 Say Hi.mp3",title:"Say Hi",artist:"Eshen",coverUrl:"B:/python-test/project2/public_GUI/cover/Say Hi.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-33 Feast of Spring.mp3",title:"Feast of Spring",artist:"K-Run & M2U",coverUrl:"B:/python-test/project2/public_GUI/cover/Feast of Spring.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-34 ¤³¤Îº£¤Ë±§¤«¤ì¤Æ (PSV ED2).mp3",title:"¤³¤Îº£¤Ë±§¤«¤ì¤Æ",artist:"Tzu-Chieh Wen, Masaki Baba",coverUrl:"B:/python-test/project2/public_GUI/cover/¤³¤Îº£¤Ë±§¤«¤ì¤Æ.jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-35 Goodbye (Piano Version).mp3",title:"Goodbye (Piano Version)",artist:"Chamber Chu (Tasty)",coverUrl:"B:/python-test/project2/public_GUI/cover/Goodbye (Piano Version).jpeg",},
{path:"G:/ÒôÀÖ/DEEMOÇú×Ó/11/11-36 Goodbye (PS Vita Version).mp3",title:"Goodbye (PS Vita Version)",artist:"Chamber Chu (Tasty)",coverUrl:"B:/python-test/project2/public_GUI/cover/Goodbye (PS Vita Version).jpeg",},];