const musicPath=[{path:"G:/音乐/RNB36 曲包/00.MISIA - Work It Out.mp3",title:"Work It Out",artist:"MISIA",coverUrl:"B:/python-test/project2/public_GUI/cover/Work It Out.jpeg",},
{path:"G:/音乐/RNB36 曲包/01.LOVE - 100年后のきみに.mp3",title:"100年后のきみに",artist:"LOVE",coverUrl:"B:/python-test/project2/public_GUI/cover/100年后のきみに.jpeg",},
{path:"G:/音乐/RNB36 曲包/02.Flower - あの日のさよなら.mp3",title:"あの日のさよなら",artist:"Flower",coverUrl:"",},
{path:"G:/音乐/RNB36 曲包/03.DJ KOMORI - Veronica - Girls Gotta Have Some Fun (Rishi Rich Remix) - remix.mp3",title:"Veronica / Girls Gotta Have Some Fun (Rishi Rich Remix)",artist:"DJ KOMORI",coverUrl:"B:/python-test/project2/public_GUI/cover/Veronica  Girls Gotta Have Some Fun (Rishi Rich Remix).jpeg",},
{path:"G:/音乐/RNB36 曲包/04.AISHA - Love Again.mp3",title:"Love Again",artist:"AISHA",coverUrl:"B:/python-test/project2/public_GUI/cover/Love Again.jpeg",},
{path:"G:/音乐/RNB36 曲包/05.宮脇詩音 - この世界で想うたった一人のひと.mp3",title:"この世界で想うたった一人のひと",artist:"宮脇詩音",coverUrl:"B:/python-test/project2/public_GUI/cover/この世界で想うたった一人のひと.jpeg",},
{path:"G:/音乐/RNB36 曲包/06.Bright - 言叶にできなくて.mp3",title:"言叶にできなくて",artist:"Bright",coverUrl:"B:/python-test/project2/public_GUI/cover/言叶にできなくて.jpeg",},
{path:"G:/音乐/RNB36 曲包/07.SPICY CHOCOLATE - LOVE STORY feat.Mye & SPOCK fr.mp3",title:"LOVE STORY feat.Mye & SPOCK fr",artist:"SPICY CHOCOLATE",coverUrl:"B:/python-test/project2/public_GUI/cover/LOVE STORY feat.Mye & SPOCK fr.jpeg",},
{path:"G:/音乐/RNB36 曲包/08.吉川友 - こんな私でよかったら.mp3",title:"こんな私でよかったら",artist:"吉川友",coverUrl:"B:/python-test/project2/public_GUI/cover/こんな私でよかったら.jpeg",},
{path:"G:/音乐/RNB36 曲包/09高梨マリアーニ - 君とByeByeしてから….mp3",title:"¾ý¤ÈByeBye¤·¤Æ¤«¤é¡­",artist:"¸ßÀæ¥Þ¥ê¥¢©`¥Ë",coverUrl:"",},
{path:"G:/音乐/RNB36 曲包/10.MAY'S - LOVE SONG ~今なら言えるよ~.mp3",title:"LOVE SONG ~今なら言えるよ~",artist:"MAY'S",coverUrl:"",},
{path:"G:/音乐/RNB36 曲包/11.BENI - いとしのエリー.mp3",title:"いとしのエリー",artist:"BENI",coverUrl:"B:/python-test/project2/public_GUI/cover/いとしのエリー.jpeg",},
{path:"G:/音乐/RNB36 曲包/12.傳田真央 - マニフェスト.mp3",title:"マニフェスト",artist:"傳田真央",coverUrl:"B:/python-test/project2/public_GUI/cover/マニフェスト.jpeg",},];