const musicPath=['{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-01 Suspenseful Third Day.mp3","title":"Suspenseful Third Day","artist":"Kearu Underground","coverUrl":"B:/python-test/project2/public_GUI/cover/Suspenseful Third Day.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-02 Living In The One.mp3","title":"Living In The One","artist":"Edmund Fu","coverUrl":"B:/python-test/project2/public_GUI/cover/Living In The One.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-03 Legacy.mp3","title":"Legacy","artist":"switchworks","coverUrl":"B:/python-test/project2/public_GUI/cover/Legacy.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-04 Sunset.mp3","title":"Sunset","artist":"Alex Vourtsanis","coverUrl":"B:/python-test/project2/public_GUI/cover/Sunset.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-05 Sakura iro no yume ~—@É«¤ÎÃÎ~.mp3","title":"Sakura iro no yume ~—@É«¤ÎÃÎ~","artist":"Baba Band","coverUrl":"B:/python-test/project2/public_GUI/cover/Sakura iro no yume ~—@É«¤ÎÃÎ~.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-06 La Promesse.mp3","title":"La Promesse","artist":"Cranky","coverUrl":"B:/python-test/project2/public_GUI/cover/La Promesse.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-07 ANiMA.mp3","title":"ANiMA","artist":"xi","coverUrl":"B:/python-test/project2/public_GUI/cover/ANiMA.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-08 The Beautiful Moonlight.mp3","title":"The Beautiful Moonlight","artist":"Mai Aoyagi","coverUrl":"B:/python-test/project2/public_GUI/cover/The Beautiful Moonlight.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-09 Fluquor.mp3","title":"Fluquor","artist":"onoken Vocal: Rin","coverUrl":"B:/python-test/project2/public_GUI/cover/Fluquor.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-10 Myosotis.mp3","title":"Myosotis","artist":"M2U & NICODE feat. Guriri & Lucy","coverUrl":"B:/python-test/project2/public_GUI/cover/Myosotis.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-11 Altale.mp3","title":"Altale","artist":"Sakuzyo","coverUrl":"B:/python-test/project2/public_GUI/cover/Altale.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-12 Run Lads Run.mp3","title":"Run Lads Run","artist":"Killerblood","coverUrl":"B:/python-test/project2/public_GUI/cover/Run Lads Run.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-13 Starting Wind.mp3","title":"Starting Wind","artist":"Edmund Fu","coverUrl":"B:/python-test/project2/public_GUI/cover/Starting Wind.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-14 Farewell Waltz.mp3","title":"Farewell Waltz","artist":"Moosa Shawn Nicholas(Stone)","coverUrl":"B:/python-test/project2/public_GUI/cover/Farewell Waltz.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-15 Revival.mp3","title":"Revival","artist":"TQ","coverUrl":"B:/python-test/project2/public_GUI/cover/Revival.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-16 Ark of Desire.mp3","title":"Ark of Desire","artist":"Edmund Fu","coverUrl":"B:/python-test/project2/public_GUI/cover/Ark of Desire.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-17 Futarimiti.mp3","title":"Futarimiti","artist":"Morrigan & Cranky","coverUrl":"B:/python-test/project2/public_GUI/cover/Futarimiti.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-18 Shadow in the mirror.mp3","title":"Shadow in the mirror","artist":"Abia Ng","coverUrl":"B:/python-test/project2/public_GUI/cover/Shadow in the mirror.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-19 Nightfall.mp3","title":"Nightfall","artist":"ginkiha","coverUrl":"B:/python-test/project2/public_GUI/cover/Nightfall.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-20 Yaoyue.mp3","title":"Yaoyue","artist":"gondayu","coverUrl":"B:/python-test/project2/public_GUI/cover/Yaoyue.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-21 Kimi ga Nokoshita Sekai de.mp3","title":"Kimi ga Nokoshita Sekai de","artist":"The SxPlay","coverUrl":"B:/python-test/project2/public_GUI/cover/Kimi ga Nokoshita Sekai de.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-22 Guardian.mp3","title":"Guardian","artist":"The SxPlay","coverUrl":"B:/python-test/project2/public_GUI/cover/Guardian.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-23 Rainbow\'s End.mp3","title":"Rainbow\'s End","artist":"Edmund Fu","coverUrl":"B:/python-test/project2/public_GUI/cover/Rainbow\'s End.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-24 Post-script.mp3","title":"Post-script","artist":"The Hoshizora Project","coverUrl":"B:/python-test/project2/public_GUI/cover/Post-script.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-25 H.mp3","title":"H","artist":"Orangentle","coverUrl":"B:/python-test/project2/public_GUI/cover/H.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-26 Tree of Dreams.mp3","title":"Tree of Dreams","artist":"Michiru Oshima","coverUrl":"B:/python-test/project2/public_GUI/cover/Tree of Dreams.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-27 White Rain.mp3","title":"White Rain","artist":"Michiru Oshima","coverUrl":"B:/python-test/project2/public_GUI/cover/White Rain.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-28 Infinite Puzzle.mp3","title":"Infinite Puzzle","artist":"Y-SHIN","coverUrl":"B:/python-test/project2/public_GUI/cover/Infinite Puzzle.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-29 Spring Snowflake Flower.mp3","title":"Spring Snowflake Flower","artist":"masaki kawasaki","coverUrl":"B:/python-test/project2/public_GUI/cover/Spring Snowflake Flower.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-30 Little Love.mp3","title":"Little Love","artist":"Michiru Oshima","coverUrl":"B:/python-test/project2/public_GUI/cover/Little Love.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-31 Lonely Pianist.mp3","title":"Lonely Pianist","artist":"Michiru Oshima","coverUrl":"B:/python-test/project2/public_GUI/cover/Lonely Pianist.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-32 Miracle of Daybreak.mp3","title":"Miracle of Daybreak","artist":"WhiteCapella","coverUrl":"B:/python-test/project2/public_GUI/cover/Miracle of Daybreak.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-33 Waltz in Devil\'s Playground.mp3","title":"Waltz in Devil\'s Playground","artist":"Ramenbot Jr.","coverUrl":"B:/python-test/project2/public_GUI/cover/Waltz in Devil\'s Playground.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-34 Aquamarine.mp3","title":"Aquamarine","artist":"Cashew","coverUrl":"B:/python-test/project2/public_GUI/cover/Aquamarine.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-35 Go or Stay.mp3","title":"Go or Stay","artist":"Zris","coverUrl":"B:/python-test/project2/public_GUI/cover/Go or Stay.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-36 Ruins in the Mirage.mp3","title":"Ruins in the Mirage","artist":"SIHanatsuka & Yukino","coverUrl":"B:/python-test/project2/public_GUI/cover/Ruins in the Mirage.jpeg"}',
'{"path":"G:/ÒôÀÖ/DEEMOÇú×Ó/2/2-37 White Fantasy.mp3","title":"White Fantasy","artist":"SLS","coverUrl":"B:/python-test/project2/public_GUI/cover/White Fantasy.jpeg"}',];