# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browserSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_browserSelect(object):
    def setupUi(self, browserSelect):
        browserSelect.setObjectName("browserSelect")
        browserSelect.resize(276, 360)
        self.btnBox = QtWidgets.QDialogButtonBox(browserSelect)
        self.btnBox.setGeometry(QtCore.QRect(30, 295, 221, 41))
        self.btnBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBox.setObjectName("btnBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(browserSelect)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 60, 160, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbtnDefault = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbtnDefault.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.rbtnDefault.setFont(font)
        self.rbtnDefault.setObjectName("rbtnDefault")
        self.verticalLayout.addWidget(self.rbtnDefault)
        self.rbtnChrome = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.rbtnChrome.setFont(font)
        self.rbtnChrome.setObjectName("rbtnChrome")
        self.verticalLayout.addWidget(self.rbtnChrome)
        self.rbtnFirefox = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.rbtnFirefox.setFont(font)
        self.rbtnFirefox.setObjectName("rbtnFirefox")
        self.verticalLayout.addWidget(self.rbtnFirefox)
        self.rbtnEdge = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.rbtnEdge.setFont(font)
        self.rbtnEdge.setObjectName("rbtnEdge")
        self.verticalLayout.addWidget(self.rbtnEdge)
        self.label = QtWidgets.QLabel(browserSelect)
        self.label.setGeometry(QtCore.QRect(30, 20, 211, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(browserSelect)
        self.btnBox.accepted.connect(browserSelect.accept)
        self.btnBox.rejected.connect(browserSelect.reject)
        QtCore.QMetaObject.connectSlotsByName(browserSelect)

    def retranslateUi(self, browserSelect):
        _translate = QtCore.QCoreApplication.translate
        browserSelect.setWindowTitle(_translate("browserSelect", "Dialog"))
        self.rbtnDefault.setText(_translate("browserSelect", "默认浏览器"))
        self.rbtnChrome.setText(_translate("browserSelect", "谷歌浏览器"))
        self.rbtnFirefox.setText(_translate("browserSelect", "火狐浏览器"))
        self.rbtnEdge.setText(_translate("browserSelect", "Edge浏览器"))
        self.label.setText(_translate("browserSelect", "请选择浏览器："))
